from modules.discriminators.frequency_discriminator import MultiFrequencyDiscriminator
from modules.discriminators.period_discriminator import MultiPeriodDiscriminator
from modules.discriminators.scale_discriminator import MultiScaleDiscriminator
